In [5]:
import pandas as pd
from classes.ticket import Ticket
from classes.agent import Agent
from classes.solution import Solution
from classes.ticket_assignment import TicketAssignment

In [6]:
path = "data/tech_support.db"
Ticket.path = path
Agent.path = path
Solution.path = path
TicketAssignment.path = path

In [7]:
csv_path = "G20_Tech Support â€“ Tickets  Agents with Solutions_merged.csv"
df = pd.read_csv(csv_path, delimiter=';', encoding='utf-8')
df.head()

,tickets_id,agents_id,assignment_date,resolution_time,issue,submission_date,status,solutions_id,agents_name,agents_department,email,resolution_summary,solved_date
0,1818,1,2025/01/05,64,Stop else big particularly.,2025/02/19,Open,250,Shannon Reyes,IT,dominique36@example.net,Political region wide life room letter sound t...,2025/01/30
1,276,86,2025/02/06,35,Then message suddenly practice maybe.,2025/01/11,Pending,1404,Mary Smith,Field Support,carlostravis@example.com,Candidate choice ground help large bed beautif...,2025/01/17
2,796,30,2025/01/19,40,Hour along picture until song read determine.,2025/01/14,Open,162,Chris Garcia,Field Support,john47@example.net,Foot bad hour almost lay want class some cultu...,2025/02/10
3,548,81,2025/01/12,25,But mother anything enjoy save conference ago.,2025/02/11,Open,544,William Torres,Field Support,tammy54@example.org,Decision if example will type within.,2025/01/08
4,870,63,2025/02/01,66,Color finally oil.,2025/01/04,Pending,1081,Laura Burns,Customer Service,ismith@example.com,Save bill series matter evening particular sit...,2025/02/11

In [8]:
for _, row in df.iterrows():
    Ticket(row['tickets_id'], row['issue'], row['submission_date'], row['status'])
    Agent(row['agents_id'], row['agents_name'], row['agents_department'], row['email'])
    TicketAssignment(row['tickets_id'], row['agents_id'], row['assignment_date'], row['resolution_time'])
    Solution(row['solutions_id'], row['tickets_id'], row['resolution_summary'], row['solved_date'])

In [9]:
for p in Ticket.lst:
    Ticket.insert(p)
for p in Agent.lst:
    Agent.insert(p)
for p in TicketAssignment.lst:
    TicketAssignment.insert(p)
for p in Solution.lst:
    Solution.insert(p)
print("Dados inseridos com sucesso com base na Gclass")

Dados inseridos com sucesso com base na Gclass